(function () {
  var worker = 'https://km-cms-auth.mraxlrose.workers.dev/analytics';
  var dias = 30; var metricaGrafico = 'activeUsers'; var dadosAtuais;
  var mensagem = document.getElementById('mensagem'); var painel = document.getElementById('painel');

  function tokenDaSessao() { try { var salvo = localStorage.getItem('netlify-cms-user') || localStorage.getItem('decap-cms-user'); var usuario = salvo && JSON.parse(salvo); return usuario && (usuario.token || usuario.access_token); } catch (erro) { return null; } }
  function escapar(valor) { return String(valor == null ? '' : valor).replace(/[&<>"']/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); }
  function numero(valor) { return new Intl.NumberFormat('pt-BR').format(Number(valor || 0)); }
  function percentual(valor) { return new Intl.NumberFormat('pt-BR', { style: 'percent', maximumFractionDigits: 1 }).format(Number(valor || 0)); }
  function duracao(valor) { var segundos = Math.round(Number(valor || 0)); return segundos < 60 ? segundos + ' s' : Math.floor(segundos / 60) + ' min ' + (segundos % 60) + ' s'; }
  function linhas(relatorio) { if (!relatorio || relatorio.erro || !relatorio.rows) return []; var dimensoes = (relatorio.dimensionHeaders || []).map(function (d) { return d.name; }); var metricas = (relatorio.metricHeaders || []).map(function (m) { return m.name; }); return relatorio.rows.map(function (linha) { var objeto = {}; dimensoes.forEach(function (nome, i) { objeto[nome] = linha.dimensionValues[i].value; }); metricas.forEach(function (nome, i) { objeto[nome] = linha.metricValues[i].value; }); return objeto; }); }
  function relatorio(nome) { return dadosAtuais.relatorios[nome]; }
  function tabela(destino, nomes, dados, limite) { var area = document.getElementById(destino); if (!dados.length) { area.innerHTML = '<p class="vazio">Ainda não há dados suficientes para este relatório.</p>'; return; } var maximo = Number(dados[0][nomes[1].chave] || 1); area.innerHTML = '<table class="tabela"><thead><tr>' + nomes.map(function (n) { return '<th>' + escapar(n.rotulo) + '</th>'; }).join('') + '</tr></thead><tbody>' + dados.slice(0, limite || 10).map(function (linha) { return '<tr>' + nomes.map(function (n, i) { var valor = linha[n.chave]; var exibicao = n.formato ? n.formato(valor) : escapar(valor); if (i === 0 && nomes.length > 1) exibicao += '<div class="barra"><i style="width:' + Math.min(100, Number(linha[nomes[1].chave] || 0) / maximo * 100) + '%"></i></div>'; return '<td>' + exibicao + '</td>'; }).join('') + '</tr>'; }).join('') + '</tbody></table>'; }
  function kpis() { var item = linhas(relatorio('resumo'))[0] || {}; var itens = [ ['Usuários ativos', numero(item.activeUsers)], ['Novos usuários', numero(item.newUsers)], ['Sessões', numero(item.sessions)], ['Visualizações', numero(item.screenPageViews)], ['Engajamento', percentual(item.engagementRate)], ['Tempo médio', duracao(item.averageSessionDuration)], ['Eventos importantes', numero(item.keyEvents)] ]; document.getElementById('kpis').innerHTML = itens.map(function (i) { return '<article class="kpi"><span>' + i[0] + '</span><strong>' + i[1] + '</strong></article>'; }).join(''); }
  function dataLegivel(valor) { var texto = String(valor); return texto.length === 8 ? texto.slice(6) + '/' + texto.slice(4, 6) : texto; }
  function grafico() { var pontos = linhas(relatorio('evolucao')); var valores = pontos.map(function (p) { return Number(p[metricaGrafico] || 0); }); if (!valores.length) { document.getElementById('grafico').innerHTML = '<p class="vazio">Ainda não há dados suficientes para o gráfico.</p>'; return; } var maximo = Math.max.apply(null, valores) || 1; var largura = 760; var altura = 220; var margem = 26; var passo = (largura - margem * 2) / Math.max(1, valores.length - 1); var coordenadas = valores.map(function (v, i) { return (margem + i * passo).toFixed(1) + ',' + (altura - margem - v / maximo * (altura - margem * 2)).toFixed(1); }); var area = margem + ',' + (altura - margem) + ' ' + coordenadas.join(' ') + ' ' + (largura - margem) + ',' + (altura - margem); document.getElementById('grafico').innerHTML = '<svg viewBox="0 0 ' + largura + ' ' + altura + '" role="img" aria-label="Evolução de acessos"><line x1="' + margem + '" y1="' + (altura - margem) + '" x2="' + (largura - margem) + '" y2="' + (altura - margem) + '" stroke="#dce5eb"/><path class="area" d="M ' + area + ' Z"/><polyline class="linha" points="' + coordenadas.join(' ') + '"/><text x="' + margem + '" y="16">Máximo: ' + numero(maximo) + '</text><text x="' + margem + '" y="' + (altura - 5) + '">' + dataLegivel(pontos[0].date) + '</text><text text-anchor="end" x="' + (largura - margem) + '" y="' + (altura - 5) + '">' + dataLegivel(pontos.at(-1).date) + '</text></svg>'; }
  function tempoReal() { var dados = linhas(dadosAtuais.tempoReal); var total = dados.reduce(function (soma, linha) { return soma + Number(linha.activeUsers || 0); }, 0); document.getElementById('ativos-agora').textContent = numero(total); tabela('paises-agora', [{ rotulo: 'País', chave: 'country' }, { rotulo: 'Ativos', chave: 'activeUsers', formato: numero }], dados, 5); }
  function renderizar() { kpis(); grafico(); tempoReal(); tabela('canais', [{ rotulo: 'Canal', chave: 'sessionDefaultChannelGroup' }, { rotulo: 'Sessões', chave: 'sessions', formato: numero }, { rotulo: 'Eventos', chave: 'keyEvents', formato: numero }], linhas(relatorio('canais'))); tabela('dispositivos', [{ rotulo: 'Dispositivo', chave: 'deviceCategory' }, { rotulo: 'Usuários', chave: 'activeUsers', formato: numero }], linhas(relatorio('dispositivos'))); tabela('eventos', [{ rotulo: 'Evento', chave: 'eventName' }, { rotulo: 'Ocorrências', chave: 'eventCount', formato: numero }], linhas(relatorio('eventos'))); tabela('geografia', [{ rotulo: 'Local', chave: 'city' }, { rotulo: 'Usuários', chave: 'activeUsers', formato: numero }, { rotulo: 'Sessões', chave: 'sessions', formato: numero }], linhas(relatorio('geografia'))); tabela('paginas', [{ rotulo: 'Página', chave: 'pagePath' }, { rotulo: 'Visualizações', chave: 'screenPageViews', formato: numero }, { rotulo: 'Usuários', chave: 'activeUsers', formato: numero }], linhas(relatorio('paginas'))); tabela('origens', [{ rotulo: 'Origem / meio', chave: 'sessionSourceMedium' }, { rotulo: 'Sessões', chave: 'sessions', formato: numero }, { rotulo: 'Usuários', chave: 'activeUsers', formato: numero }], linhas(relatorio('origem'))); }
  function carregar() { var token = tokenDaSessao(); if (!token) { mensagem.className = 'mensagem erro'; mensagem.textContent = 'Entre novamente no painel com o GitHub para consultar as métricas.'; return; } mensagem.hidden = false; mensagem.className = 'mensagem'; mensagem.textContent = 'Consultando Google Analytics…'; document.getElementById('atualizar').disabled = true; fetch(worker + '?days=' + dias, { headers: { authorization: 'Bearer ' + token } }).then(function (resposta) { return resposta.json().then(function (corpo) { if (!resposta.ok) { var erro = new Error(corpo.error || 'Não foi possível carregar as métricas.'); erro.setupRequired = corpo.setupRequired; throw erro; } return corpo; }); }).then(function (dados) { dadosAtuais = dados; mensagem.hidden = true; painel.hidden = false; document.getElementById('atualizacao').textContent = 'Dados dos últimos ' + dias + ' dias · atualizado em ' + new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(dados.geradoEm)); renderizar(); }).catch(function (erro) { painel.hidden = true; mensagem.hidden = false; mensagem.className = 'mensagem erro'; mensagem.textContent = erro.setupRequired ? 'A integração ainda precisa ser ativada no Google Cloud e no Cloudflare. Consulte as instruções do projeto.' : erro.message; }).finally(function () { document.getElementById('atualizar').disabled = false; }); }
  document.querySelectorAll('[data-days]').forEach(function (botao) { botao.addEventListener('click', function () { dias = Number(botao.dataset.days); document.querySelectorAll('[data-days]').forEach(function (outro) { outro.classList.toggle('ativo', outro === botao); }); carregar(); }); });
  document.querySelectorAll('[data-metric]').forEach(function (botao) { botao.addEventListener('click', function () { metricaGrafico = botao.dataset.metric; document.querySelectorAll('[data-metric]').forEach(function (outro) { outro.classList.toggle('ativo', outro === botao); }); if (dadosAtuais) grafico(); }); }); document.getElementById('atualizar').addEventListener('click', carregar); carregar();
})();
